### PR TITLE
Task #2 create movies and the unit test

### PR DESCRIPTION
**Pull request by ChaChang-Byte**
Completed task #2 for app.py, create_movies_form.html and unit test. Need to finish E2E later. Thanks

### CODE REVIEW

**Review by weiraven — APPROVED** [review]
Looks good to me!

**Comment by brandonhach** [comment]
LGTM

**Comment by weiraven** [comment]
Merged Phillip's branch per Discord group chat. HE WATCHED ME DO IT.

**Comment by brandonhach** [comment]
( ͡° ͜ʖ ͡°)

**Pull request merged**
